### ISSUE TITLE
not exactly an issue with thi s package

### ISSUE THREAD

**Issue by michapixel** [app-generator/eleventy-html5up-miniport#2]
but i was recently using eleventy and was in need of a bundler too.
i'm quasi using your package-scripts but am unable to use eleventy's watch, internal server and webpack in watch-mode. 

Am i right, that this project does only bundle js while initially rund not live/watching for changes?

**Comment by app-generator** [comment]
Hello @michapixel, 
Thanks for using our products. The app is **watching** the njk files under *yarn dev* target. 
You can extend the watch to the JS/CSS files. Pretty sure 11ty supports this.
